// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package order_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OrderSvcClient is the client API for OrderSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderSvcClient interface {
	//订单详情
	GetOrderDetails(ctx context.Context, in *GetOrderDetailsReq, opts ...grpc.CallOption) (*GetOrderDetailsResp, error)
}

type orderSvcClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderSvcClient(cc grpc.ClientConnInterface) OrderSvcClient {
	return &orderSvcClient{cc}
}

func (c *orderSvcClient) GetOrderDetails(ctx context.Context, in *GetOrderDetailsReq, opts ...grpc.CallOption) (*GetOrderDetailsResp, error) {
	out := new(GetOrderDetailsResp)
	err := c.cc.Invoke(ctx, "/order.OrderSvc/GetOrderDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderSvcServer is the server API for OrderSvc service.
// All implementations must embed UnimplementedOrderSvcServer
// for forward compatibility
type OrderSvcServer interface {
	//订单详情
	GetOrderDetails(context.Context, *GetOrderDetailsReq) (*GetOrderDetailsResp, error)
	mustEmbedUnimplementedOrderSvcServer()
}

// UnimplementedOrderSvcServer must be embedded to have forward compatible implementations.
type UnimplementedOrderSvcServer struct {
}

func (UnimplementedOrderSvcServer) GetOrderDetails(context.Context, *GetOrderDetailsReq) (*GetOrderDetailsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderDetails not implemented")
}
func (UnimplementedOrderSvcServer) mustEmbedUnimplementedOrderSvcServer() {}

// UnsafeOrderSvcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderSvcServer will
// result in compilation errors.
type UnsafeOrderSvcServer interface {
	mustEmbedUnimplementedOrderSvcServer()
}

func RegisterOrderSvcServer(s grpc.ServiceRegistrar, srv OrderSvcServer) {
	s.RegisterService(&OrderSvc_ServiceDesc, srv)
}

func _OrderSvc_GetOrderDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderDetailsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderSvcServer).GetOrderDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderSvc/GetOrderDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderSvcServer).GetOrderDetails(ctx, req.(*GetOrderDetailsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderSvc_ServiceDesc is the grpc.ServiceDesc for OrderSvc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderSvc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order.OrderSvc",
	HandlerType: (*OrderSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrderDetails",
			Handler:    _OrderSvc_GetOrderDetails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order.proto",
}
