[server]
#正式服配置端口
addr = "0.0.0.0:1801"
#调试模式
mode = false
#注册服务发现 etcd地址
etcd = "http://127.0.0.1:2379"
#./config/etcd.pem
etcd_cert = ""
#./config/etcd-key.pem
etcd_key = ""
#./config/etcd-ca.pem
etcd_ca_cert = ""

[grpc_cli.order]
#订单服务发现
prefix = "/services/order/"
[grpc_cli.mp]
#小程序服务发现
prefix = "/services/mp/"


#系统云行日志配置
[runLog]
#日志文件路径
file = "./log/run.log"
#所有级别日志文件最大存储大小，级别单独配置将覆盖此值
maxSize = 100
#所有级别日志文件备份个数，级别单独配置将覆盖此值
maxBackups = 10
#所有级别日志文件最大存储时间，单位：天，级别单独配置将覆盖此值
maxAge = 30
#日志级别
level = "error"

#服务访问日志
[accessLog]
#访问日志文件
file = "./log/access.log"
#所有级别日志文件最大存储大小，级别单独配置将覆盖此值
maxSize = 100
#所有级别日志文件备份个数，级别单独配置将覆盖此值
maxBackups = 10
#所有级别日志文件最大存储时间，单位：天，级别单独配置将覆盖此值
maxAge = 30

#系统sql日志配置
[sqlLog]
#日志文件路径
file = "./log/sql.log"
#所有级别日志文件最大存储大小，级别单独配置将覆盖此值
maxSize = 100
#所有级别日志文件备份个数，级别单独配置将覆盖此值
maxBackups = 10
#所有级别日志文件最大存储时间，单位：天，级别单独配置将覆盖此值
maxAge = 30
#日志级别
level = "debug"

#数据库配置
[db.default]
#数据库驱动
driver = "mysql"
dsn = "root:mysql@tcp(127.0.0.1:33066)/gateway?charset=utf8mb4&parseTime=True&loc=Local"
#空闲数大小
max_idle = 10
#最大打开连接数
max_open = 30
#最大生存时间(ms)
max_life = 100
#是否显示SQL
show_sql = true
#表名前缀
prefix = ""
#单数表名
singular = true
#日志等级(gorm)
level = "info"
#从
[[db.default.slave]]
dsn = "root:mysql@tcp(127.0.0.1:33066)/gateway?charset=utf8mb4&parseTime=True&loc=Local"

#redis配置
[redis]
network = "tcp"
# len >1 为集群模式否则为单机模式
addr = ["127.0.0.1:6379"]
#redis数据库编号0-15取值
db = 5
#密码
password = ""
#有值则为哨兵模式
master_name = ""
#连接池配额
pool_size = 10
#最小空闲连接配额
idle_conns = 10

#mongodb 配置 库名
[mongo.test]
#地址
addr = "mongodb://root:mongodb@127.0.0.1:27017/?authSource=admin"
#超时时间
max_idle_time = 10
#连接池最大数量
max_pool = 180
#连接池最小数量
min_pool = 10
#用户名
username = "root"
#密码
password = "mongodb"

#mongodb 配置 库名
[mongo.deng]
#地址
addr ="mongodb://root:mongodb@127.0.0.1:27017/?authSource=admin"
#超时时间
max_idle_time = 10
#连接池最大数量
max_pool = 180
#连接池最小数量
min_pool = 10
#用户名
username = "root"
#密码
password = "mongodb"

#登陆相关配置
[login]
total = 5
time = 600
key = "9c585bc02b29f7718f6d15cab687ac19"
timeout = 36000

#elasticsearch配置
[elastic]
#主机地址
host = "http://127.0.0.1:9200"
#用户名
username = "elastic"
#密码
password = "123456"
#是否开启集群嗅探
sniff = false
#设置两次运行状况检查之间的间隔(s)
heal = 120
#启用或禁用gzip压缩
gzip = false

#对称加密
[encryption]
key = "aFs25NHp2Kt8KYw6HxNZmET0"
iv = "t19yZlW85z59RBTF"

##七牛云配置
[qi_niu]
access_key = "h1b_lFiE6FstO-zHFCPYGaPs_p8epO4nqPkQPoTO"
secret_key = "Sszf1I9qvxiDiYn7F2GWqpvpAo0vsXmz7dB5xhFW"
bucket = "blogdeng"
domain = "https://ltdyxdqq.com"

##阿里云oss配置
[ali_oss]
access_key = "LTAI5tHMQcBvThYx8NBKaXN1"
secret_key = "TPiurIDtppN6XpNIA5EnPzpog31LBX"
bucket = "blogdeng"
domain = "https://alioss.ltdyxdqq.com"